### ISSUE TITLE
Sublime go-to-definition is supported out the box

### ISSUE THREAD

**Issue by Jayflux** [contradictioned/areweideyet#37]
https://areweideyet.com/

Shows Sublime go to definition as  supported via racer and plugin, but its there on base install (Sublime Text 3)
The same for code completion too

**Comment by contradictioned** [comment]
I'd argue, that in order to get the most of code completion and goto definition, you still should use racer. Sublime only shows a list of things in the current project it believes to be the original definition, while racer understands the language.

Altough I really enjoy the new additions of Sublime (especially for smaller Ruby-projects), I'll let the table as it is. But I'll add this aspect to the infobox below.
