### ISSUE TITLE
Rusty Code is abandoned

### ISSUE THREAD

**Issue by gcp** [contradictioned/areweideyet#41]
The page currently lists RustyCode for Visual Studio Code, however, that actually seems abandoned:
https://github.com/saviorisdead/RustyCode/issues/177

It's old enough that most functionality has been broken by changes in stable Rust.

Combined with it being the most downloaded extension if you search for Rust in the VSCode extension repo, that probably means most people will be mislead into installing an extension that actually no longer works for the most part.

I recommend RustyCode is removed from the Visual Studio Code list, and that it points to the "Rust" extension instead:
https://github.com/KalitaAlexey/vscode-rust

which is actively maintained (so far 😀).

**Comment by thomanski** [comment]
RustCode worked ok for what I did (just editing and running tests, no debugging) except it didn't parse errors correctly. When this became too much of an annoyance I eventually sought out solutions and thankfully came across this issue with it's pointer to vscode-rust.

Since It was indeed areweideyet that had initially led me to RustyCode I agree it'd be nice to update the page at the very least with a remark that RustyCode seems to presently be unmaintained and that vscode-rust is a presently maintained alternative.

**Comment by contradictioned** [comment]
Thanks for the hints! I keep Rusty Code as historic reference (maybe also as a hint to change the plugin)

**Comment by flying-sheep** [comment]
this change hasn’t made it onto the site yet. do you have to update it manually?

**Comment by contradictioned** [comment]
Yes, I am just working on the other issues and do a single update afterwards :)
