### ISSUE TITLE
Update IntelliJ IDEA section

### ISSUE THREAD

**Issue by johnthagen** [contradictioned/areweideyet#49]
[IntelliJ IDEA](https://intellij-rust.github.io/) table entry should be updated as following:

- Linting: supported by plugin
- Code Formatting: supported by plugin
- Debugging: ✔³ supported by plugin when using CLion

I would also suggest that under important packages section for Intellij, the `intellij-rust` link be updated to its homepage: https://intellij-rust.github.io/

**Comment by contradictioned** [comment]
Thanks for the input!
I added the debugging-check mark without 3, but added a comment to the text box below. As in the [FAQ](https://intellij-rust.github.io/docs/faq.html) debugging is said to be preliminarily supported (and the disussion also makes that impression), I also mentioned it like this for now.

**Comment by BatmanAoD** [comment]
@contradictioned The discussion on the intellij-rust issue for debugging support now makes it clear that debugging will probably _never_ come to IDEA, so it may be worth listing IDEA and CLion in separate rows. (I'd say just list CLion instead of IDEA, but it doesn't actually have a community edition, so that's not really a viable solution. Sigh.)

**Comment by johnthagen** [comment]
FWIW, if your work is open source, you can apply for a free CLion license: https://www.jetbrains.com/community/opensource/

I realize this is not the same as a community edition though.

**Comment by BatmanAoD** [comment]
@johnthagen Thanks! For the purpose of areweideyet, though, I think it's important not to make such assumptions about users.
