### ISSUE TITLE
Visual Studio Code should have its own section separate to Visual Studio?

### ISSUE THREAD

**Issue by gilescope** [contradictioned/areweideyet#73]
Also maybe link to the second gen rust IDE:

https://github.com/rust-analyzer/rust-analyzer

**Comment by Pfeil** [comment]
For me, there are already separate rows in the table for VS Code and for Visual Studio. So I don't actually understand to what exactly you are referring to.

Since rust-analyzer in general seems to be far from production ready, I personally would not list it with the rls plugins yet, but it could be mentioned somewhere so it gets some attention.

**Comment by gilescope** [comment]
Thanks - if people don't know about rust-analyser they can't help. Snowball
effects and all that.

Agreed it's early days but I have high hopes for it.

**Comment by Pfeil** [comment]
That was just a personal opinion, I do not have influence in how things are done on this site ;)
When I read about rust analyzer I was happy to see that there are people working on a better solution, although the RLS is working pretty ok for my use cases.

Can you explain what you tried to describe with the issues title?

**Comment by contradictioned** [comment]
Hey, yeah VS Code and Visual Studio are quite clearly separated in the editor and the IDE section.

I have thought about making an extra box about the non-editor part of the ecosystem (clippy, rls, ...) maybe this would be the place for rust-analyzer. But for now, I don't see how rust-analyzer could directly be useful for rust users.
